spring:
  datasource:
    url: jdbc:mysql://localhost/bankdb?createDatabaseIfNotExists=true
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: bhagya.ariyarathne.online@gmail.com
    password: ljdz herw nolv zstn
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
